CREATE TABLE [dbo].[PlayerRegister] (
    [PlayerRegisterId]   INT              IDENTITY (1, 1) NOT NULL,
    [FirstName]          VARCHAR (50)     NULL,
    [LastName]           VARCHAR (50)     NULL,
    [Gender]             VARCHAR (20)     NULL,
    [City]               VARCHAR (100)    NULL,
    [MobileNo]           NVARCHAR (50)    NULL,
    [AlternativePhoneNo] NVARCHAR (50)    NULL,
    [Email]              NVARCHAR (100)   NULL,
    [DOB]                DATE             NULL,
    [Batsman]            BIT              NULL,
    [Bowler]             BIT              NULL,
    [WicketKeeper]       BIT              NULL,
    [BattingAllRounder]  BIT              NULL,
    [BowlingAllRounder]  BIT              CONSTRAINT [DF_PlayerRegister_BowlingAllRounder] DEFAULT ((0)) NULL,
    [LastPlayedYear]     DATE             NULL,
    [ProfilePicture]     NVARCHAR (MAX)   NULL,
    [Password]           NVARCHAR (MAX)   NULL,
    [BasePrice]          DECIMAL (10, 2)  NULL,
    [WinningBid]         DECIMAL (10, 2)  NULL,
    [UpdatedOn]          DATETIME         CONSTRAINT [DF_PlayerRegister_UpdatedOn] DEFAULT (getdate()) NULL,
    [CreatedOn]          DATETIME         CONSTRAINT [DF_PlayerRegister_CreatedOn] DEFAULT (getdate()) NULL,
    [CreatedBy]          UNIQUEIDENTIFIER CONSTRAINT [DF_PlayerRegister_CreatedBy] DEFAULT ('E39F47A6-1C9B-4BB7-8AB1-67D6B8BB541B') NULL,
    [UpdatedBy]          UNIQUEIDENTIFIER CONSTRAINT [DF_PlayerRegister_UpdatedBy] DEFAULT ('E39F47A6-1C9B-4BB7-8AB1-67D6B8BB541B') NULL,
    [IsDeleted]          BIT              NULL,
    [IsActive]           BIT              NULL,
    [PreviousTeamId]     INT              NULL,
    [SortByType]         VARCHAR (50)     NULL,
    [SortByIndex]        INT              NULL,
    [PlayerCategory]     VARCHAR (50)     NULL,
    [PlayerNo]           INT              NULL,
    [PlayerGroupId]      INT              NULL,
    CONSTRAINT [PK_PlayerRegister_New] PRIMARY KEY CLUSTERED ([PlayerRegisterId] ASC)
);



